# Generated by Django 5.0.3 on 2024-04-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_alter_userpreference_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='avoided_genres',
            new_name='preferred_actors',
        ),
        migrations.RenameField(
            model_name='userpreference',
            old_name='preferred_languages',
            new_name='preferred_directors',
        ),
        migrations.RenameField(
            model_name='userpreference',
            old_name='watch_frequency',
            new_name='preferred_keywords',
        ),
    ]
