# Generated by Django 5.0.3 on 2024-04-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('runtime', models.IntegerField()),
                ('collection_name', models.CharField(blank=True, max_length=255, null=True)),
                ('production_company_names', models.TextField()),
                ('keywords_list', models.TextField()),
                ('writers', models.TextField()),
                ('producers', models.TextField()),
                ('release_year', models.IntegerField()),
                ('popularity_scaled', models.FloatField()),
                ('weighted_rating', models.FloatField()),
                ('working_poster_url', models.URLField(max_length=1024)),
                ('actors', models.ManyToManyField(to='movies.actor')),
                ('directors', models.ManyToManyField(to='movies.director')),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
